[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "certifi>=2025.8.3",
    "flask>=3.1.2",
    "httpx>=0.27.0",
    "openai>=1.107.3",
]
